//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YalWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>!ddg|https://duckduckgo.com/?q=%1</string>
  <string>!g|https://www.google.com/?q=%1</string>
  <string>!w|https://en.wikipedia.org/w/index.php?title=Special:Search&amp;profile=default&amp;fulltext=Search&amp;search=%1</string>
  <string>!a|https://www.amazon.com/s/field-keywords=%1</string>
  <string>!yt|https://www.youtube.com/results?search_query=%1</string>
  <string>!so|http://stackoverflow.com/search?q=%1</string>
  <string>!imdb|http://www.imdb.com/find?s=all&amp;q=%1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Entries {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Entries"]));
            }
            set {
                this["Entries"] = value;
            }
        }
    }
}
