//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YalCommand.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>~reboot|%windir%\system32\shutdown.exe|-r -t 00|True</string>
  <string>~shutdown|%windir%\system32\shutdown.exe|-s -t 00|True</string>
  <string>~cmdrun|%windir%\system32\cmd.exe|/C !1!|False</string>
  <string>~nopen|%windir%\system32\notepad.exe|!1!|False</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Entries {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Entries"]));
            }
            set {
                this["Entries"] = value;
            }
        }
    }
}
